### ISSUE TITLE
Nuget download fail.

### ISSUE THREAD

**Issue by lanpst** [Efferent-Health/HL7-dotnetcore#1]
thanks for this project which is great for IVD software work with LIS or HIS.
I try to download the project through Nuget but fail.
the environment here is .NETFramework,Version=v4.5.2 in Windows Form project.
Does this library only work in .net core?

--- Lan from China / sunlyk@qq.com

**Comment by jaime-olivares** [comment]
Hi Lan, this project is specific for dotnetcore, as we couldn't find one suitable. If you still want to use, you should migrate to .net 4.6.1, which is currently the most recommended framework. You will be able to use almost any dotnetcore (netstandard) library.

**Comment by lanpst** [comment]
Thanks. I will update .net to 4.6.1.
-------------------------------------------------------------
I focus on medical device control software on PC part with Windows Form. 
Our product cover 2 filed: immuno-histo-chemistry, coaguration.
how about u?
