### ISSUE TITLE
Serialize with validation fails

### ISSUE THREAD

**Issue by abcdefgabcefg** [Efferent-Health/HL7-dotnetcore#101]
Hi, I'm trying to serialize and validate the `Message` object. So, I
1. Create `Message` object
2. Add segments
3. Call `SerializeMessage(true)`

I expect the message to fail validation with an appropriate message
Actually, I got _Failed to validate the message with error - No Message Found_ exception

You could see sample [here](https://github.com/abcdefgabcefg/LH7Reproduce/blob/master/HL7Reproduce/Program.cs)

Is it a bug or did I do something wrong?

**Comment by jaime-olivares** [comment]
Hi,
I can see you are lacking a header segment, to start with.

**Comment by abcdefgabcefg** [comment]
@jaime-olivares Hi, thanks for your help!
Sorry for that sample what I really meant is it seems like the No Message Found exception doesn't depend on the validity of the message((( It is thrown for any message, even for invalid.
Please, check [this sample](https://github.com/abcdefgabcefg/LH7Reproduce/blob/master/ValidMessage/Program.cs). It generates a valid message (validated with [this tool](http://try-it.caristix.com:9030/default.aspx)) but the No Message Found exception is still thrown.

**Comment by jaime-olivares** [comment]
I see what you are doing.
The validation is performed for messages coming from strings.
As your message has been created on the fly, there is nothing to validate. It is implicitly valid.
Anyway, in case you want to force validation, you would need a trick like this one:

````
        var s1 = message.SerializeMessage(false);
        var m1 = new Message(s1);
        m1.SerializeMessage(true);
````
