### ISSUE TITLE
Error message typo "beggining"

### ISSUE THREAD

**Issue by Cam-Woods** [Efferent-Health/HL7-dotnetcore#102]
In src/Message.cs this exception is thrown:

throw new HL7Exception("MSH segment not found at the beggining of the message", HL7Exception.BAD_MESSAGE);

There is a spelling error where "beggining" should be "beginning".

Thanks,

Cam

**Comment by jaime-olivares** [comment]
That typo was fixed some time ago. Are you sure you are using the last version?

**Comment by Cam-Woods** [comment]
I may not be on the latest version.  I did a code search in GitHub and found the line of code I referenced so I was assuming it was still in the codebase.  Maybe that was found in an older version of the file.  If so I apologize for the confusion.  I should have checked the resolved issues.
