### ISSUE TITLE
Messages are limited to 32767 segments . Have undefined results after that

### ISSUE THREAD

**Issue by tkent** [Efferent-Health/HL7-dotnetcore#103]
A `short` is used to manage the sequence number for segments ([here](https://github.com/Efferent-Health/HL7-dotnetcore/blob/d71debe7e64035e4c9c85b9455948ab173cdbe6c/src/Segment.cs#L9))

For messages with > 32767 segments, you run over max value that can be held by a short. We occasionally need to process messages of this size and get undefined results. 

Simply swapping the data type to a `long` would fix the issue. For reference, from the HL7v2 spec.

> HL7 sets no limits on the maximum size of HL7 messages.

**Comment by jaime-olivares** [comment]
Changed to the datatype to `int`. No need to change to `long` which is even larger. 
Already published in version [2.8](https://www.nuget.org/packages/HL7-dotnetcore/2.28.0)
