### ISSUE TITLE
Strong name for assembly inside nuget package

### ISSUE THREAD

**Issue by ALittleDruid** [Efferent-Health/HL7-dotnetcore#104]
It is recommended to add a strong name to the library

https://github.com/DeepLcom/deepl-dotnet/issues/7#issue-1119575306

**Comment by jaime-olivares** [comment]
From the Microsoft's document [here](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named):

>For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

As this is a .NET Core/.NET 5+ product, I don't see any benefit. Moreover, adding a strong name will overcomplicate the deployment.
