### ISSUE TITLE
Accept <segment_name>(<segment_number).<field_number> request in Message.GetValue(string strValueFormat)

### ISSUE THREAD

**Issue by bokc** [Efferent-Health/HL7-dotnetcore#105]
It will be helpfull to accepte <segment_name>(<segment_number).<field_number> request in Message.GetValue(string strValueFormat)

for exemple : OBX(1).4

**Comment by drewkill32** [comment]
you should already be able to do this by using

```csharp
 message.GetValue("OBX.1.4");
```

**Comment by bokc** [comment]
> you should already be able to do this by using
> 
> ```cs
>  message.GetValue("OBX.1.4");
> ```
Not exactly. What you propose : 
`message.GetValue("OBX.2.4") => message.Segments("OBX")[0].Fields(2).Components(4).Value;
`
What I need:
`message.GetValue("OBX(2).4") => message.Segments("OBX")[1].Fields(4).Value;
`

**Comment by drewkill32** [comment]
why can't you modify the string before passing it into `message.GetValue()`?

**Comment by jaime-olivares** [comment]
Merged PR #106

Available in version 2.32+
