### ISSUE TITLE
Assigned value not showing when segment printed

### ISSUE THREAD

**Issue by jmergens1** [Efferent-Health/HL7-dotnetcore#107]
I assign a value top PID.4.1 and when I print the PID or add it to a message the value is blank.
I can access it through the Segment and message but it does not show when printed other than explicitly calling the field.
I can also access all other fields and they print out with the segment just fine
Can someone explain this to me?

**Comment by jaime-olivares** [comment]
Please provide some concrete source code

**Comment by healukas** [comment]
From your description I am assuming that you are trying something like this: 
```csharp
var message = new Message(content);
message.ParseMessage();
message.Segments("PID")[0].Fields(4).Components(1).Value = "SomeValue";

Console.WriteLine(message.HL7Message);
```
If my assumption is correct, changing the last line to 
```csharp
Console.WriteLine(message.SerializeMessage(false));
``` 
should do the trick.

**Comment by jaime-olivares** [comment]
closing as there is no more feedback
