### ISSUE TITLE
X-escape sequence decoding

### ISSUE THREAD

**Issue by mansell72** [Efferent-Health/HL7-dotnetcore#108]
The current decoding of X-escape sequences produces incorrect results for the double-byte and triple-byte characters I'm working with.  

Your implementation, where the hex value is converted to an `int` and cast to a `char` appears to be suited for single-byte characters, and does not work for the double and triple byte escape sequences I sometimes get.
I am currently pre-processing messages to decode X-escape sequences _by instead converting the hex value to a `byte[]`  and then decoding it to UTF-8_ prior to using HL7-dotnetcore for parsing (which has otherwise been fantastic to use in our project btw :))

So instead of this:
`char decoded = (char)int.Parse(hexString)`

I'm doing something like this:
`    byte[] characterBytes = Enumerable.Range(0, hexString.Length).Where(x => x % 2 == 0).Select(x => Convert.ToByte(hexString.Substring(x, 2), 16)).ToArray();`
`    Encoding utf8 = new UTF8Encoding();`
`    string decoded = utf8.GetString(characterBytes);`

This works for me when decoding German prescription directions like this:
`T\XC3A4\glich 1 Tablette oral einnehmen.`
It decodes to this:
`Täglich 1 Tablette oral einnehmen.`

And for (simplified) Chinese directions like this:
`\XE6AF8F\\XE5A4A9\\XE69C8D\\XE794A8\.`
it decodes to this:
`每天服用.`

I think you could improve your X-escape decoding routine with similar approach.  Doing it with the byte array and UTF8Encoding still works for single-byte characters (e.g. \X2E\) btw.

**Comment by jaime-olivares** [comment]
Hi @mansell72,
thanks for reviewing this.
You are welcome to provide a pull request with your proposal and unit tests

**Comment by jaime-olivares** [comment]
Solved in the last commit. Available in nuget version 2.35
