### ISSUE TITLE
Question: Package not built in 'Release' mode?

### ISSUE THREAD

**Issue by DavidErben** [Efferent-Health/HL7-dotnetcore#109]
I was just running benchmarks of my application with Benchmark.NET and when I benchmark code using the library I get the following exception:

`Assembly XXX which defines benchmarks references non-optimized HL7-dotnetcore`
`If you own this dependency, please, build it in RELEASE.`

Is this possible? If I grab the code, run `dotnet publish -c Release -f netstandard2.0` and copy the DLL manually into my benchmark project, the exception goes away.

If it is really published in debug mode, could you please publish the package built with release mode? Thanks! 👍 

P.S. I know that this error can be deactivated in Benchmark.NET, but published libraries should always be published with release mode to ensure the code is optimized!

**Comment by jaime-olivares** [comment]
Version 2.31 is now in Release mode
