### ISSUE TITLE
Escaping sequences

### ISSUE THREAD

**Issue by testlorenzospa** [Efferent-Health/HL7-dotnetcore#110]
Hello.

I am trying to use this library. However, I have a problem.

In an HL7 message (ADT-A28), in field 5 components 1 subcomponent 1 I have a string like that
AAA\F\aa&

Now, when I call the function
message.Segments("PID")[0].Fields(5).Components(1).SubComponents(1).Value
the value returned has the sequences escaped.

But, if I remove the & (or the subcomponent) and I call the function
message.Segments("PID")[0].Fields(5)..Components(1).Value
the value returned has not the sequences escaped.

Why have I this behavior?
How can I solve it?

**Comment by testlorenzospa** [comment]
Hello.

For getting some help, I put here the message HL7 that I am trying to read with this library.
Probably, is a my wrong syntax the problem.

```
MSH|^~\&|SAP|aaa|JCAPS||20210330150502||ADT^A28|0000000111300053|P|2.5||||||UNICODE UTF-8
EVN||20210330150502
PID|||704251200^^^SAP^PI^0001~XXXXXXX^^^SS^SS^066^20210330~""^^^^PRC~""^^^^DL~""^^^^PPN~XXXXXXXX^^^Ministero finanze^NN~""^^^^PNT^^^""~""^^^^NPI^^""^^""&&""^""&""||TEST\F\TEST^TEST2^^^SIG.^""||19610926|M|||^^SANTEUSANIO FORCONESE^^^IT^BDL^^066090~&VIA DELLA PIEGA 12 TRALLaae^""^SANTEUSANIO FORCONESE^AQ^67020^IT^L^^066090^^^^20210330||^ORN^^^^^^^^^^349 6927621~^NET^^""|||2||||||||||IT^^100^Italiana|||""||||20160408
PD1|||AVEZZANO-SULMONA-LAQUILA^^^^^^ASLR^^^130201||||||||""^^HSR^0001^XXXXXXXX^YYYY NK1|1||SEL|||||""|||07||""^^""
NK1|2|""^""
NK1|3|""^""
NK1|4||SEL|||||19900101||||||||||||||P^Consenso Rilasciato|||||||||||OSR-DSDP^^^^^^19900101
NK1|5||SEL|||||20160408||||||||||||||P^Consenso Rilasciato|||||||||||OSR-TD^^^^^^20160408
NK1|6||SEL|||||20210325||||||||||||||P^Consenso Rilasciato|||||||||||OSR-MI^^^^^^20210325
NK1|7||SEL|||||20210325||||||||||||||P^Consenso Rilasciato|||||||||||OSR-DC^^^^^^20210325
NK1|8||SEL|||||20210325||||||||||||||P^Consenso Rilasciato|||||||||||OSR-RD^^^^^^20210325
PV1||N||||||||||||||N
PV2||||||||||||||||||||||||ATTIVO
```

**Comment by jaime-olivares** [comment]
Solved in the last commit. Use Nuget version 2.33. Please confirm.
