### ISSUE TITLE
Generate a ACK bases on a HL7 message with MSH.2 = ^~&

### ISSUE THREAD

**Issue by adescalzo** [Efferent-Health/HL7-dotnetcore#112]
According to the documentation on some sites like  [HL7 v2.5.1 - MSH.2 - Encoding Characters](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Fields/MSH.2), the recommended value for MSH.2 is `^~\&`, but it is possible to set `^~&` ([HL7 MSH (Message Header)](https://rhapsody.health/resources/hl7-msh-message-header/))

There is a case where we should allow a message with the value `^~&`, but when the ACK is trying to be generated, the follow exception happens

Exception: "Failed to validate the message with error - MSH.9 not available"

This is the test to reproduce this issue:

       [TestMethod]
        public void GenerateAckTest()
        {
            var sampleMessage = @"MSH|^~&|EPIC||||20191107134803|ALEVIB01|ORM^O01|23|T|2.3|||||||||||";
            sampleMessage = $"{sampleMessage}\nPID|1||MRN_123^^^IDX^MRN||Smith F S R E T^John||19600101|M";

            var message = new Message(sampleMessage);
            message.ParseMessage();
            var ack = message.GetACK();

            var ACK_MSH_2 = ack.GetValue("MSH.2");
            var MSG_MSH_2 = message.GetValue("MSH.2");

            Assert.AreEqual(ACK_MSH_2, "^~&");
            Assert.AreEqual(MSG_MSH_2, "^~&");
        }

**Comment by jaime-olivares** [comment]
I am able to reproduce the issue. Analysis in progress...

**Comment by jaime-olivares** [comment]
I have reviewed the documentation from the links.

The first document tells that delimiters field has a length of 4. Other possible lengths are not mentioned.

The second document seems to have a buggy formatting. The backslash character is never shown. I think it is some HTML rendering issue.

Please provide any other document where it is explicitly stated that the delimiters field can have only 3 characters.

**Comment by jaime-olivares** [comment]
This change it is already published in nuget version 2.36

**Comment by adescalzo** [comment]
@jaime-olivares Thanks

**Comment by JarodChay** [comment]
@jaime-olivares, this change seems to be unnecessary.
> I found it by myself. There is a formal definition in http://www.hl7.eu/HL7v2x/v21/std21/KAP2.html

The change contradicts the definition for the sub-component separator.
> 2.3.2.3 Sub-Component Separator.
The sub-component separator is used to separate adjacent sub-components of some data fields. Its use is described in the descriptions of the relevant data fields. The character that represents the sub-component separator is specified for each message as the fourth character in the Encoding Characters data field of the MSH segment.

If you accept `^~&` as a valid value for MSH.2 then the sub-component separator is no longer the fourth character.

The page referenced by @adescalzo (https://rhapsody.health/resources/hl7-msh-message-header/) does seem to have a problem rendering the backslash character. If you look at the table of recommended values, you'll see that the Escape character row has no value in the CHARACTER column. This contradicts the definition for the escape character that you previously quoted. This would add weight to the theory that the `MSH|^~&|...` example may be incorrect and is a victim of buggy formatting.
> Absent other considerations it is recommended that all sending applications use '\\' as the escape character.

Coincidentally, the above quoted sentence required me to escape the backslash with another backslash. :)
