### ISSUE TITLE
Parse failure with double-encoded values

### ISSUE THREAD

**Issue by eldorturgunov** [Efferent-Health/HL7-dotnetcore#117]
Parse fails for the following message:

```
MSH|^~\&|Main_HIS|XYZ_HOSPITAL|iFW|ABC_Lab|20160915003015||ACK|9B38584D|P|2.6.1|
MSA|AA|9B38584D|Double encoded value: \E\T\E\|
```
`msg.ParseMessage()` returns `false`. `msg.SerializeMessage(false)` returns:
```
MSH|^~\&|Main_HIS|XYZ_HOSPITAL|iFW|ABC_Lab|20160915003015||ACK|9B38584D|P|2.6.1|
MSA|AA|9B38584D|Double encoded value: \T\|
```
At SubComponent level `\E\T\E\` is decoded as `&` rather than `\T\`.

**Comment by jaime-olivares** [comment]
Use version https://www.nuget.org/packages/HL7-dotnetcore/2.37.0
