### ISSUE TITLE
Add model binding

### ISSUE THREAD

**Issue by kfrancis** [Efferent-Health/HL7-dotnetcore#12]
I've created a very simple attribute/model binding addition. Wondering if you would like it included. The problem I was solving with your code was parsing a message into a model, but I was getting tired of writing the same code over and over. What I've come up with is the following:

Let's say you have a Patient object that you need to get data in from the HL7 message. In the end, what you call is like this.

```c#
    Message message = new Message(strMsg);
    message.ParseMessage(); // For brevity, don't check.
    Patient patient = message.Bind<Patient>();
```

Bind is an extension method (for now), but it works because the fields of `Patient` are decorated with custom attributes like this:

```c#
    public class Patient {
        [HL7StringField("ERQ", Field=4)]
        public string HealthNumber { get;set; }

        [HL7DateTimeField("PID", Field=3, Component=2, Repetition=2, Format="yyyyMMddd")]
        public string DateTime BirthDate { get; set; }

        [HL7EnumField("PID", Field=3, Component=3, SubComponent=1, EnumType=typeof(Gender))]
        public Gender Gender { get;set; }

        // etc
    }
```

It works absolutely brilliantly, I think it would be a good addition to your library as filling a model is most likely one of first things people want to do with a parsed HL7 message.

Let me know if you would like this as a PR.

**Comment by kfrancis** [comment]
If you're wondering why there are different custom attributes, I decided on that in favour of a required type param - though it could work either way. It's too bad there can't be `HL7Field<string>("ERQ", Field=4)` - not allowed unfortunately. All of those attributes do implement the same `IHL7Field<T>` interface, but different attributes for the implementations.

**Comment by jaime-olivares** [comment]
Hi there, 
This looks like a good idea. However, I wouldn't use custom entities when you can use a well-established schema like FHIR .Net API (see https://github.com/ewoutkramer/fhir-net-api).
Although it may be complicated to add attributes to the existing entities, you may create maps for relating entities' properties with HL7 positions, as extension methods.
Anyway, that deserves be put in a separated github project, triangulating with this one and the other mentioned project.

**Comment by jaime-olivares** [comment]
I still think this should not be incorporated in this project, either you use a standard entity schema or not. Different developers may prefer different entity containers and even mapping mechanisms, so it won't be practical to choose one in particular and it will be complex to create a pluggable infrastructure. So, I will invoke the Separation of Concerns concept and keep this out of this project.
