### ISSUE TITLE
Consideration to targeting netcore

### ISSUE THREAD

**Issue by wokket** [Efferent-Health/HL7-dotnetcore#124]
Hi all,

We're loving the lightweight minimal nature of this library, but suspect there's significant performance gains to be had by _actually_ targetting netcore/modern .net instead/as well as netstandard2.

If you're open to multi-targetting both netstandard for older clients and modern .net then there's obviously many optimisations in play (Source generated regex, span support replacing nested stringbuilders etc).

Is this something you'd be open to?  This repo doesn't seem hugely active given the long-standing issues/possible fixes in open PR's so if you'd prefer to leave this as-is I'll fork a copy for our org and go from there 👍

Cheers

**Comment by jaime-olivares** [comment]
Hi wokket,
We can collaborate as far as you send a different PR for each change, with a previous discussion phase for each one.
We need to take care of legacy, as we have dozens of 3rd party projects using this library.

**Comment by wokket** [comment]
I fully appreciate the need for back compat/maintaining compliance with the spec :)

Before I make any changes, was there a plan to complete the outstanding bug fix PRs/release a new version?  Trying to decide where to start for making changes.

**Comment by jaime-olivares** [comment]
I merged a PR that should solve all issues. Use https://www.nuget.org/packages/HL7-dotnetcore/2.37.0

**Comment by wokket** [comment]
Did you intend to publish a Debug version of the library?  I'm getting warning from Benchmark.net when I reference the nuget package:
![image](https://github.com/Efferent-Health/HL7-dotnetcore/assets/3802829/2b46c61c-c9e4-4acd-86a4-fba1e6b388c9)

**Comment by jaime-olivares** [comment]
I didn't make any change in the build pipeline

**Comment by jaime-olivares** [comment]
I have verified with the nuget package inspector that the unique configuration published is Release.

Regarding that particular message, I read that it may be related to a missing `<Optimize>true</Optimize` csproj configuration.

Try with the following deployment and let me know: https://www.nuget.org/packages/HL7-dotnetcore/2.37.1-beta1

**Comment by wokket** [comment]
Yep, that's resolved the error (and can't hurt perf 👍 ).  

Thanks for looking into it so quickly.

**Comment by jaime-olivares** [comment]
I have migrated the Azure DevOps pipeline to GitHub Actions, and added NET 8 in the target list. 
Pushed to a beta package: https://www.nuget.org/packages/HL7-dotnetcore/2.38.3-beta1

You can play with it. Let me know if it is already presenting performance improvements.

**Comment by wokket** [comment]
Thanks mate.  I've just updated the benchmark in my local WIP branch, and can confirm there's definately performance improvements just from targeting net8 specifically:

```

| Method                   | Job          | Runtime            | NuGetReferences            | Mean     | Ratio | Gen0    | Gen1   | Allocated | Alloc Ratio |
|------------------------- |------------- |------------------- |--------------------------- |---------:|------:|--------:|-------:|----------:|------------:|
| ParseMessageAndGetValues | Local Net4.8 | .NET Framework 4.8 | Default                    | 75.53 us |  1.44 | 32.5928 | 4.3945 | 200.57 KB |        0.95 |
| ParseMessageAndGetValues | Local Net8   | .NET 8.0           | Default                    | 36.40 us |  0.70 |  9.3994 | 1.3428 | 144.08 KB |        0.68 |
| ParseMessageAndGetValues | Nuget Net4.8 | .NET Framework 4.8 | HL7-dotnetcore 2.37.1      | 97.78 us |  1.87 | 44.4336 | 6.7139 | 273.48 KB |        1.30 |
| ParseMessageAndGetValues | Nuget Net4.8 | .NET Framework 4.8 | HL7-dotnetcore 2.38        | 96.54 us |  1.84 | 40.5273 | 6.1035 | 249.26 KB |        1.18 |
| ParseMessageAndGetValues | Nuget Net4.8 | .NET Framework 4.8 | HL7-dotnetcore 2.38.3-beta | 96.63 us |  1.85 | 40.5273 | 6.1035 | 249.26 KB |        1.18 |
| ParseMessageAndGetValues | Nuget Net8   | .NET 8.0           | HL7-dotnetcore 2.37.1      | 52.33 us |  1.00 | 13.7329 | 2.3193 | 211.17 KB |        1.00 |
| ParseMessageAndGetValues | Nuget Net8   | .NET 8.0           | HL7-dotnetcore 2.38        | 49.26 us |  0.94 | 12.2070 | 2.0752 | 187.36 KB |        0.89 |
| ParseMessageAndGetValues | Nuget Net8   | .NET 8.0           | HL7-dotnetcore 2.38.3-beta | 45.57 us |  0.87 | 11.7798 | 1.9531 |  180.7 KB |        0.86 |

```

Note the last two lines: 7% runtime and 3% (7kb) memory improvement in net8 for the beta compared to 2.38

**Comment by wokket** [comment]
The top 2 lines show the current state of my perf branch.  If you're interested in a further 20% improvement (no net8 spoecific code) I'll get that to PR for you....

**Comment by jaime-olivares** [comment]
Ok, good to know. I will publish it as 2.39 and close this issue.

**Comment by jaime-olivares** [comment]
Done. See https://www.nuget.org/packages/HL7-dotnetcore/2.39.0
