### ISSUE TITLE
Can't build MSH Segment

### ISSUE THREAD

**Issue by StefanoD** [Efferent-Health/HL7-dotnetcore#17]
Hi,
I could not find an example how I create a MSH segment.
Here is a minimal example what I tried:

```C#
[Fact]
public void Escaping()
{
	Segment mshSeg = new Segment("MSH", new HL7Encoding());
	mshSeg.AddNewField(@"^~\&", 1);

	Message message = new Message();
	message.AddNewSegment(mshSeg);
	var str = message.SerializeMessage(false);

	Assert.Equal("MSH|^~\\&\r", str);
}
```
Unfortunatelly I get following error:
```
HL7.Dotnetcore.HL7Exception : Invalid escape sequence in HL7 string
```
This happens in `HL7Encoding.Decode()`.

Am I creating a MSH segment the wrong way or is this a bug?

**Comment by jaime-olivares** [comment]
This seems to be a duplicated of issue https://github.com/Efferent-Health/HL7-dotnetcore/issues/7 
Please have a look at the suggested workaround.
I will create soon a `CreateMessageHeader()` method.
