### ISSUE TITLE
Parsing long message

### ISSUE THREAD

**Issue by kfrancis** [Efferent-Health/HL7-dotnetcore#19]
If I attempt to parse a long message (this one in particular contains large amounts of Base64 encoded data in the form of GIF/PNG/PDF/JPG/TIF, nothing breaks but the parsing is incomplete.

I've tried "cheating" a bit and breaking up the message to circumvent any internal length restriction that's happening during parsing like so: 

```c#
    public bool ParseAllMessage(HL7.Dotnetcore.Message message)
    {
        try
        {
            var hl7 = message.HL7Message;
            var segments = hl7.Split('\r').ToList();

            List<string> hl7SubBlocks = new List<string>();
            int counter = 0;
            string currentBlock = "";
            string msh = "";
            List<string> waitingSegments = new List<string>() { "MSH", "MSA", "QAK", "ERQ", "PID", "PV1", "ORC", "OBR", "ZBR", "BLG", "OBX", "ZBX", "NTE", "ZNT" };
            foreach (var segment in segments)
            {
                if (segment.Substring(0, 3) == "MSH") msh = segment;
                if (waitingSegments.Contains(segment.Substring(0, 3))) waitingSegments.Remove(segment.Substring(0, 3));
                currentBlock += segment + '\r';
                if (segment.Substring(0, 3) == "BLG" && waitingSegments.Count == 0) counter++;
                if (counter >= 5)
                {
                    hl7SubBlocks.Add(currentBlock);
                    currentBlock = "";
                    counter = 0;
                }
            }

            foreach (var hl7SubBlock in hl7SubBlocks)
            {
                HL7.Dotnetcore.Message tmpMessage = new HL7.Dotnetcore.Message(msh+'\r'+hl7SubBlock);
                tmpMessage.ParseMessage();
                foreach (var innerSegment in tmpMessage.Segments())
                {
                    message.Segments(innerSegment.Name).Add(innerSegment);
                }
            }
            return true;
        }
        catch (Exception ex)
        {
            return false;
        }
    }
```

But this doesn't have the desired effect. I can't just add the segment data in this way. Is there an internal limit being placed on the parse method? I don't see it in your code, though stepping through it is in the next step.

**Comment by jaime-olivares** [comment]
Hi Kori, can you send me a sample message? I will test it and see where it stops.

**Comment by StefanoD** [comment]
@kfrancis 
Is this issue resolved?

**Comment by jaime-olivares** [comment]
Reopening…

**Comment by Kulak** [comment]
I just run into possibly similar issue.  The fix was to change to RegexOptions.Singleline:

        public static string[] ExtractMessages(string messages)
        {
            var expr = "\x0B(.*?)\x1C\x0D";
            var matches = Regex.Matches(messages, expr, RegexOptions.Singleline);  <-- fix

**Comment by jaime-olivares** [comment]
Thanks, I will try it

**Comment by kfrancis** [comment]
@StefanoD My comments would have been off topic. That fix by @Kulak does seem to work.

**Comment by jaime-olivares** [comment]
It is now published in NuGet.org as version 2.7.0
