### ISSUE TITLE
Value "present but null" vs Empty

### ISSUE THREAD

**Issue by Aaron-P** [Efferent-Health/HL7-dotnetcore#28]
In HL7 section 2.5.3.0, Field or Component Status, it specifies that a field value of "" (e.g. |""|) is considered to be a null value and should not be used for any other purpose.  In the parser, a field value of "" is returned as a string value of 2 double quotes, not a null string value.

**Comment by jaime-olivares** [comment]
That's a very weird one. I will review it soon.

**Comment by jaime-olivares** [comment]
Please provide a code snippet to demonstrate that behavior

**Comment by jaime-olivares** [comment]
Solved. Unit test added.
