### ISSUE TITLE
Empty fields at the end of segments are ommitted

### ISSUE THREAD

**Issue by mb2o** [Efferent-Health/HL7-dotnetcore#3]
Empty fields at the end of segments are ommitted.

E.g. it seems:
`ORC|RO|2001290459^CS|||A|F|^^^20171102^^R|||||I12007^Doe, D.|CHI||||E||`

becomes:
`ORC|RO|2001290459^CS|||A|F|^^^20171102^^R|||||I12007^Doe, D.|CHI||||E`

and therefore the entire message is never succesfully parsed!

**Comment by jaime-olivares** [comment]
This has been solved in code. Will appear soon in the nuget package 2.3

**Comment by jaime-olivares** [comment]
This should be solved now.
