### ISSUE TITLE
Incorrect fix for the "Present but null"-issue (see #28)

### ISSUE THREAD

**Issue by EliasHeydrich** [Efferent-Health/HL7-dotnetcore#32]
You have added a Unit Test when fixing #28 however this seems incomplete. Modify the test as follows:

```
[Test]
public void EmptyAndNullFields()
{
      const string sampleMessage = "MSH|^~\\&|SA|SF|RA|RF|20110613083617||ADT^A04|123|P|2.7||||\r\nEVN|A04|20110613083617||\"\"";

      var message = new Message(sampleMessage);

      //the changed part:
      var parseResult = message.ParseMessage();
            Assert.That( parseResult, Is.True, "!!> FAILED TO PARSE A MESSAGE HERE IN THE TEST <!!" );
            Assert.That( message.SegmentCount, Is.GreaterThan(0), "!!> FAILED TO PARSE A MESSAGE HERE IN THE TEST, PRODUCED ZERO SEGMENTS <!!" );

       var evn = message.Segments("EVN")[0];

       var expectEmpty = evn.Fields(3).Value;
       Assert.AreEqual(string.Empty, expectEmpty);
       var expectNull = evn.Fields(4).Value;
       Assert.AreEqual(null, expectNull);
}
```

Now, the test fails. Aka your test message is not being parsed correctly and the behavior of 2.10 is actually rather undefined.

**Comment by jaime-olivares** [comment]
Will review for next release. If you know the solution, please post a PR.

**Comment by chrismidolo** [comment]
The fix is to add logic Encoding.Encode to return \\"\\" when the value is null rather than returning null as is currently the case. 

This will return the nulls to the serialised message and fix your serialisation check.

If you like I can try to do a PR.

**Comment by jaime-olivares** [comment]
yes, please, that would help

**Comment by chrismidolo** [comment]
PR submitted
