### ISSUE TITLE
Nuget Package contains unoptimised build

### ISSUE THREAD

**Issue by wokket** [Efferent-Health/HL7-dotnetcore#33]
When referencing the published nuget package (v2.10.0) BenchmarkDotNet fails with the following error:
```
Assembly ConsoleApp1 which defines benchmarks references non-optimized HL7-dotnetcore
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can create custom config with DontFailOnError to disable our custom policy and allow this benchmark to run.
```
Given the performance critical nature of most HL7 codebases publishing an optimised release build seems worthwhile 👍

**Comment by jaime-olivares** [comment]
Solved. Will be published in Release mode in 2.11
