### ISSUE TITLE
ParseTest() and HL7_ADT

### ISSUE THREAD

**Issue by qagwaai** [Efferent-Health/HL7-dotnetcore#34]
Running ParseTest with Message based on HL7_ADT which points to Sample-ADT.txt returns isParsed = false.

on or thereabouts line 111, there is the following:

`if (this.Equals(strSerializedMessage))
   isParsed = true;`

this fails because the two messages are different in that the original has a blank segment and therefore 5 segments instead of the parsed version which has 4.

is it true that a Message would not be equivalent if the difference were extra blank segments?

**Comment by jaime-olivares** [comment]
The issue was due to a blank line in Sample-ADT.txt

Now the parser handles it correctly.
