### ISSUE TITLE
github release notes

### ISSUE THREAD

**Issue by amccool** [Efferent-Health/HL7-dotnetcore#38]
any chance to get a github release created and matched to a nupkg?

**Comment by jaime-olivares** [comment]
there is already a nuget package. What else is needed?

**Comment by amccool** [comment]
its very nice to be able to be the release notes when the nupkg is created from your build proc.

**Comment by amccool** [comment]
to point - what is the build proc?

**Comment by jaime-olivares** [comment]
The build is defined in azure-pipelines.yml

**Comment by amccool** [comment]
> just looking for the ceremony
