### ISSUE TITLE
Parsing DateTimes

### ISSUE THREAD

**Issue by PendelinP** [Efferent-Health/HL7-dotnetcore#39]
It would be great to have a helper method to parse a DateTime value field in the following format "YYYY[MM[DD[HH[MM[SS[.S[S[S[S]]]]]]]]][+/-ZZZZ]". 

See documentation: http://www.hl7.eu/refactored/dtDTM.html

**Comment by jaime-olivares** [comment]
Hi @PendelinP,
I understand your requirement, but the proposed PR doesn't seem to cover many cases, like these:

- Date with decimal point
- Date with intermediate digits of sub-seconds (different than 2 or 5)
- Date with time-zone sign and digits
- Combinations sub-seconds and time-zone digits

I will use another approach using regex and publish soon.

**Comment by Aaron-P** [comment]
I've done something sort of similar if it would be helpful.

[DTM.txt](https://github.com/Efferent-Health/HL7-dotnetcore/files/3307250/DTM.txt)

**Comment by jaime-olivares** [comment]
Already implemented a new method and added a big bunch of unit tests. There is a second method that returns also time-zone offset.

See [nuget package 2.14](https://www.nuget.org/packages/HL7-dotnetcore/2.14.0)

**Comment by PendelinP** [comment]
Awesome! Thanks a lot ;)
