### ISSUE TITLE
Access/mutate a specific component in a repeated field?

### ISSUE THREAD

**Issue by mb2o** [Efferent-Health/HL7-dotnetcore#4]
How do I access the value 13000722 ?

`PID|1||13000722^^^CS^PI^^^~154921123^^^NLMINBIZA^NNNLD^^20120425^~""^^^NLMINBIZA^PPN~4866812344^^^NLRDW^DL~""^^^NLIND^CZ~""^^^NLMINBUZA^CZ ...`

This works:
`message.Segments("PID")[0].Fields(3).Repetitions(1).Components(1).Value`

But what if I want to use a syntax like `message.getValue("PID.3.1")`

**Comment by jaime-olivares** [comment]
There is not support for doing that using a field locator string.

However, I will consider that for future versions.
