### ISSUE TITLE
Request breaking API change: MessageHelper.ParseDateTime

### ISSUE THREAD

**Issue by danm-de** [Efferent-Health/HL7-dotnetcore#44]
Looking at Microsoft's base types like `int`, `DateTime` or `DateTimeOffset` I can find two different kinds of parsing methods:
- `DataType.Parse(...)` that returns `DateType` or throws an informative exception if parsing somehow fails. 
- `DataType.TryParse(...)` that returns `true` + *out parameter* or `false` if parsing was not successful.  

Returning `DateTime?` (nullable type) as option type is a well known pattern from FP languages. However, it prevents me from seeing the exact exception message. I'd suggest three signatures:
- `DateTime ParseDateTime(string value)` (this one throws exceptions. Cannot be added because it conflicts with the current signature)
- `DateTime? TryParseDateTime(string value)` (option type, Try* indicates it could return `null`)
- `bool TryParseDateTime(string value, out DateTime result)` (old fashion Try-Pattern)

**Comment by jaime-olivares** [comment]
I have attended this requirement without adding a breaking-change.
See the README, commit https://github.com/Efferent-Health/HL7-dotnetcore/commit/610c78aa902739631e90c1d35a8a89d621c07e18 and Nuget package [2.15.0](https://www.nuget.org/packages/HL7-dotnetcore/2.15.0)
