### ISSUE TITLE
Repeating Fields

### ISSUE THREAD

**Issue by ccyoucc** [Efferent-Health/HL7-dotnetcore#45]
Good evening,
First of all, thank you for this project,  it is very helpful.

I have problem, because in my program I have to add into the segment PID, a repeating field, for the phone and mobile numbers, but unfortunately I do not have access to the internal RepeatitionList property.

Can you tell me how can I implement this, without changing the accessibility operator?
 I need this output : 

PID||||||||||||||(0033)4521254215^PRN^PH~(0033)62512455^ORN^CP~^NET^Internet^addresse@email.test

Best regards,
Constantin

**Comment by jaime-olivares** [comment]
Hi, I will look for it soon. 

My understanding is that you want to append another value to an existing [repeatable] field.

**Comment by robepstein** [comment]
I have the exact same problem. I'm needing to programmatically add a Repetition to a given Field. I thought I might be able to do this by setting HasRepetitions to true, but unfortunately, the Repetitions public function DOES NOT leverage the RepeatitionList internal property. Instead it references the _RepetitionList member field directly. Inspection of the code shows that the RepeatitionList internal property isn't used anywhere in the Field class currently.

I would be happy to submit a PR with this change if you'd like.

**Comment by robepstein** [comment]
I made the change discussed above regarding Repetitions returning RepeatitionList and it solved my problem. Happy to submit the change if it would help. Cheers.

**Comment by jaime-olivares** [comment]
please post a pull request and I will review it as soon as possible

**Comment by robepstein** [comment]
PR posted

**Comment by jaime-olivares** [comment]
reviewing

**Comment by jaime-olivares** [comment]
I have performed the merge. Still reviewing other use-cases

**Comment by Ravenheart** [comment]
Is there an ETA for this when it will appear on the Nuget feed?

**Comment by jaime-olivares** [comment]
Already published. Please check.

**Comment by jaime-olivares** [comment]
Closing as didn't receive more feedback
