### ISSUE TITLE
Feature: access segment repititions via SetValue and GetValue

### ISSUE THREAD

**Issue by andirapandi** [Efferent-Health/HL7-dotnetcore#48]
First off, thanks for nhapi alternative. Nhapi just does too many checks (no one implements the norm anyway - it seems) and throws totally meaningless and confusing errors.

As for multiple segment-repititions, you have an example on how to access it directly using the Segments property.

But.. I mostly use the SetValue and GetValue functions. Could you add the ability to reference segment repitions there too? I tried to google a syntax, I think others (nhapi??) do it with the repetition number in (braces), like DG1(2).2.1, not sure about best syntax though.

Also, sorry to mix 2 things here, for me I found it useful to have a SetValue and GetValue that always succeeds (never throws but just returns null or empty) and created some helpers for that. I don't know whether it would be an idea to add that code here.

**Comment by jaime-olivares** [comment]
Let's merge this issue with #45
