### ISSUE TITLE
Can you release debug on nuget?

### ISSUE THREAD

**Issue by waleswood** [Efferent-Health/HL7-dotnetcore#49]
Can you release debug on nuget? So that I could debug without referencing the source code

**Comment by jaime-olivares** [comment]
I will do soon

**Comment by jaime-olivares** [comment]
I have reviewed this and found that it is not recommended to publish release and debug together in the same Nuget Package.
I suggest to insert the full source code of hl7-dotnetcore as a project in case you want to debug internally.
