### ISSUE TITLE
When generating NACK

### ISSUE THREAD

**Issue by Hanwen196** [Efferent-Health/HL7-dotnetcore#52]
Hi, I am trying to generate negative ack and got some problem, it said "Key not found", see the picture below.

Any idea on how to resolve this?

![image](https://user-images.githubusercontent.com/10524800/74304501-4aefc880-4db1-11ea-8166-54187f077384.png)

**Comment by jaime-olivares** [comment]
Hi, I cannot reproduce this issue without the original message

**Comment by jaime-olivares** [comment]
Closing as didn't receive more feedback
