### ISSUE TITLE
Field IsSubComponentized edge case

### ISSUE THREAD

**Issue by franjom** [Efferent-Health/HL7-dotnetcore#55]
Hi.
I believe I have found a bug.
I believe that the boolean property IsComponentized on a field should be TRUE if the field consists only of one component which is SubComponentized and nothing else.
Example of that is OBR segment and field 33, which can have 11 components.
However this is what I get in a message:
|23&xxx&yyy&&&&&&zzz|

This is FIELD 33 => COMPONENT1 => SUBCOMPONENTS [1...9]
The IsComponentized for this field returns FALSE, I believe it should return TRUE and one (1) component with subcomponents. Am I right or am I doing something wrong?

**Comment by jaime-olivares** [comment]
The intent of IsComponentized is to tell if a field has more than one component. It is not affected by sub-components of a single component.
