### ISSUE TITLE
Tab space will cause message to fail

### ISSUE THREAD

**Issue by shenjeff** [Efferent-Health/HL7-dotnetcore#57]
When parsing a message, a tab space will be treated as white space and after the message is parsed, is no longer equal to the original message, causing the message parsed to fail the final check.

**Comment by jaime-olivares** [comment]
Interesting. Was that tab space necessary?

**Comment by shenjeff** [comment]
It was part of a freetext field, but I can't find anything in the HL7 specification that a tab space is an illegal character unless I am mistaken.

**Comment by jaime-olivares** [comment]
Solved. Have a look at nuget version 2.18
