### ISSUE TITLE
field repetitions

### ISSUE THREAD

**Issue by andirapandi** [Efferent-Health/HL7-dotnetcore#58]
When accessing a field with a specified repetition, the library wrongly returns the value of the first repetition if there are no others.

So

getting from "PV1.8(2).1"

will return value from "PV1.8.1"

if there are no repetitions.

This could be fixed in Message.cs getField e. g. by replacing

            if (field.HasRepetitions)
                field = field.RepeatitionList[repetition];

            return field;

with

            if (field.HasRepetitions)
                return field.RepeatitionList[repetition];
            else if (repetition == 0)
                return field;
            else
                return null;

Not beautiful, maybe you see something better.
Also, there is a typo, "RepeatitionList".

**Comment by jaime-olivares** [comment]
Hi @andirapandi 
Do you have a sample HL7 to test with?

**Comment by andirapandi** [comment]
The repetitions are in the PV1 physician fields.
Please also have a look if I missed any patient- or customer-related data that I did not anonymize.

MSH|^~\&|SYSTEM1|ABC|SYSTEM2||201803262027||DFT^P03|20180326202737608457|P|2.3||||||8859/1
EVN|P03|20180326202540
PID|1|0002381795|0002381795||Supermann^Peter^^^Herr||19990101|M|||Hamburgerstrasse 123^^Mimamu^BL^12345^CH||123456~123456^^CP||D|2|02|321|8.2.24.|||
PV1||A|00004620^00001318^1318||||000123456^Superfrau^Maria W.^|^Superarzt^Anton^L|00097012345^Superarzt^Herbert^~~0009723456^Superarzt^Markus^||||||||000998765^Assistent A^ONKO^D||0087123456||||||||||||||||||||2140||O|||201905220600|201908201100|||||
FT1|1|99987||201806281725||Charge|W32.N36|Treatment Text 1||1|||2140|||^Ihre Abteilung- RO||A|C71.8^^I10|000123456^Superfrau^Maria ^|||||W32.N36|
ZCH||99989^Linac C|RT12|12_FKA CBCT p.V.ab2F|Treatment Text 2|||W32.N36|W32.N36||||W32.N36||||||MZ/Termin|ProcLabel2|MZ kurz|ProcLabel4|ProcLabel5|Metaziffer|736988||000123456^Superfrau^Maria|

**Comment by jaime-olivares** [comment]
Done. It will throw an exception if the repetition cardinal is non-existent.
Deployed in version 2.23 ( https://www.nuget.org/packages/HL7-dotnetcore/2.23.0 )
