### ISSUE TITLE
(optionall) Automatically add elements on write access

### ISSUE THREAD

**Issue by andirapandi** [Efferent-Health/HL7-dotnetcore#59]
When I set a value on any level, this only works for already existing elements.

But.. sometimes, when I set a value, I don't want to care if the value is existing and want a convenient way of saying something like SetOrAddAndSetThen. That would be a variation of the existing

        public bool SetValue(string strValueFormat, string strValue)

in Message.cs.

I already implemented this in a local copy, though it is not really nice (a little bit forced) and also now have to merge it each time there is a change in the library code.

**Comment by jaime-olivares** [comment]
Hi @andirapandi ,
You don't need to implement a local copy each time. You can use an extension method. Have you tried?

**Comment by andirapandi** [comment]
No, I haven't. I am reusing some of the logic to get the indices (segment, field, etc.), but of course it would be cleaner to have the code somewhere else and just copy the not that complicated logic to go where one wants.
I would got that route then for the future.
Still, isn't this an adequate feature request? For me, using the access like "FT1,5,3" is the way to go when programming on arbitrary messages, and some people want data in some crazy fields or even repetitions.

**Comment by avatejo** [comment]
Hi @jaime-olivares, first have to say thank you, nice code.

I'm implementing the same feature for HL7-dotnetcore. Create the object model when the SetValue is need it.

I create some new classes on the same namespace HL7.Dotnetcore and that works for me.

Any plans to add new features to the library, including: Create the object model when the SetValue method is called.

**Comment by jaime-olivares** [comment]
guys, please send me some sample code for evaluating

**Comment by jaime-olivares** [comment]
Closed due to lack of additional information.

**Comment by KevinBassaDevelopment** [comment]
Hi, this would be a really good feature, please consider opening it again.

`Message.SetValue(string strValueFormat, string strValue) ` should also work when adding new fields instead of throwing an exception.

So basically the same behaviour that is implemented in 
`FieldCollection.Add()`
and
`ComponentCollection.Add()`,
where the parent is filled with empty components/fields when none exist yet.

**Comment by KevinBassaDevelopment** [comment]
Extension like this:
`     public static bool SetValueSave(this Message message, string key, string value)
        {
            try
            {
                key = key.Replace("-", ".");
                var keys = key.Split('.');
                var segmentKey = keys[0];
                var segment = message.Segments(segmentKey).FirstOrDefault();
                if (segment == null)
                {
                    segment = new Segment(segmentKey, new HL7Encoding());
                    message.AddNewSegment(segment);
                }

                if (keys.Length > 1)
                {
                    var fieldKey = keys[1];
                    var fieldIndex = int.Parse(fieldKey);
                    var field = segment.Fields(fieldIndex);
                    if (field == null)
                    {
                        field = new Field(new HL7Encoding());
                        segment.AddNewField(field, fieldIndex);
                    }

                    if (keys.Length > 2)
                    {
                        var componentKey = keys[2];
                        var componentIndex = int.Parse(componentKey);
                        var component = field.Components(componentIndex);
                        if (component == null)
                        {
                            component = new Component(new HL7Encoding());
                            field.AddNewComponent(component, componentIndex);
                        }
                    }
                }

                return message.SetValue(key, value ?? "");
            }
            catch (Exception e)
            {
                return false;
            }
        }`
