### ISSUE TITLE
HL7 Message object has zero segments although the message string contains segments

### ISSUE THREAD

**Issue by olaf-svenson** [Efferent-Health/HL7-dotnetcore#63]
I want to parse incoming HL7 ADT messages and create HL7 ACK messages as responses. I created the following code based on the samples from the docs

- https://github.com/Efferent-Health/HL7-dotnetcore#message-extraction
- https://github.com/Efferent-Health/HL7-dotnetcore#generate-acks

```cs
    string messageString = "\vMSH|^~\\&|KISsystem|ZTM|NIDAklinikserver|HL7Connector|201902271130||ADT^A01|68371142|P|2.3\rEVN|A01|201902271130|201902271130\rPID|1||677789||Aubertin�^Letizia||19740731|F||\rPV1|1|O|||||||||||||||||456456456\rIN1|1||999567890|gematik Musterkasse1GKV||||||||||||Prof. Dr.Aubertin�^Letizia||19740731|||||||||||201902271101|||||||X110173919\u001c\r"
    string[] hl7MessageStrings = MessageHelper.ExtractMessages(messageString);

    foreach (string hl7MessageString in hl7MessageStrings)
    {
        /* 
            hl7MessageString has almost the same 
            content as messageString but without the 
            prefixes and suffixes. The content is:

            "MSH|^~\\&|KISsystem|ZTM|NIDAklinikserver|HL7Connector|201902271130||ADT^A01|68371142|P|2.3\rEVN|A01|201902271130|201902271130\rPID|1||677789||Aubertin�^Letizia||19740731|F||\rPV1|1|O|||||||||||||||||456456456\rIN1|1||999567890|gematik Musterkasse1GKV||||||||||||Prof. Dr.Aubertin�^Letizia||19740731|||||||||||201902271101|||||||X110173919"
        */

        Message hl7Message = new Message(hl7MessageString);
        List<Segment> segments = hl7Message.Segments(); // This has a count of 0
        Message ackMessage = hl7Message.GetACK(); // This throws an exception, because MSH is missing
    }
```

When generating the ACK message I get the following exception

> System.Collections.Generic.KeyNotFoundException: The given key 'MSH'
> was not present in the dictionary.

but the MSH segment is present? How can I fix this?

**Comment by jaime-olivares** [comment]
I suspect the incoming message may contain control characters before MSH. Try to examing that string in hex/ASCII view.

**Comment by olaf-svenson** [comment]
@jaime-olivares I just updated it while debugging. Does the updated question help?

**Comment by jaime-olivares** [comment]
It seems you are missing  `hl7Message.ParseMessage()` before calling `GetAck()`

**Comment by olaf-svenson** [comment]
oh yeah .. this wasn't clear to me .. I thought `ExtractMessages` would do this already. Thanks! :)

**Comment by olaf-svenson** [comment]
@jaime-olivares  If you want I could add this information to the docs. If PRs are welcome :)

**Comment by jaime-olivares** [comment]
Hi Olaf, I was doing that right now. Thanks!

**Comment by olaf-svenson** [comment]
Ok cool :)
