### ISSUE TITLE
Encode messages for MLP

### ISSUE THREAD

**Issue by olaf-svenson** [Efferent-Health/HL7-dotnetcore#64]
When sending back ACK messages I'm currently doing

```cs
Message ackMessage = hl7Message.GetACK();
string ackMessageString = ackMessage.HL7Message;
byte[] ackMessageBytes = Encoding.UTF8.GetBytes(ackMessageString);
// ... Send message via TCP ...
```

The problem is that `ackMessageString` does not contain the pre- and suffixes required for the MLP. This package is able to parse message strings containing those pre- and suffixes as desribed here

https://github.com/Efferent-Health/HL7-dotnetcore#message-extraction

but is it also able to encode messages back to strings? My current dirty solution would be something like this:

```cs
string ackMessageString = $"{(char) 11}{ackMessage.HL7Message}{(char) 28}{(char) 13}";
```

but maybe the package is able to do it for me :)

**Comment by matthiashermsen** [comment]
I think this should do the trick

```cs
Message ackMessage = hl7Message.GetACK();
string ackMessageString = ackMessage.HL7Message;
byte[] ackMessageBytes = MessageHelper.GetMLLP(ackMessageString);
```

As you can see here

https://github.com/Efferent-Health/HL7-dotnetcore/blob/master/src/MessageHelper.cs#L97

the code is similiar to yours.
