### ISSUE TITLE
Message string is too short to get parsed

### ISSUE THREAD

**Issue by olaf-svenson** [Efferent-Health/HL7-dotnetcore#67]
I'm using the tool 7Edit to send HL7 messages from my application to the 7Edit HL7 listener for testing purposes.

My TCP socket receives the following NACK response message (I converted the bytes to a string)

> \vNACK\u001c\r

```cs
// This returns an array with 1 element with the content "NACK"
string[] hl7MessageStrings = MessageHelper.ExtractMessages(responseString);
    
// Parse the message strings to HL7 message objects
Message[] hl7Messages = hl7MessageStrings
    .Select(hl7MessageString =>
    {
        Message hl7Message = new Message(hl7MessageString);                        
        hl7Message.ParseMessage();

        return hl7Message;
    })
    .ToArray();
```

When parsing the HL7 message it throws the following exception

> Failed to validate the message with error - Message Length too short:
> 4 chars.

The code fails because of the `validateMessage` method. I found it at

https://github.com/Efferent-Health/HL7-dotnetcore/blob/master/src/Message.cs#L699

So does 7Edit send invalid response messages? Is it a little bug in this package? The 7Edit log clearly shows its response here

![image](https://user-images.githubusercontent.com/69137963/95562342-536dd100-0a1c-11eb-8725-d320f4cc3a6c.png)

and I'm not sure if they are missing the MSH segment.

**Comment by jaime-olivares** [comment]
That short response doesn't look as a valid HL7 NACK message. Don't try to parse with ParseMessage().
Have a look at http://www.interfaceware.com/manual/anatomy_of_an_ack_nack_message.html

**Comment by olaf-svenson** [comment]
@jaime-olivares so you think 7Edit seems to send back an invalid response? The response string "NACK" is not enough, the response should be this?

![image](https://user-images.githubusercontent.com/69137963/95822920-10b63c80-0d2d-11eb-89a1-459a8b201986.png)
