### ISSUE TITLE
Parse message throws exception

### ISSUE THREAD

**Issue by Fjsmoreira** [Efferent-Health/HL7-dotnetcore#68]
The parse throws an exception if it can't parse the message.
The expected behavior based on the method should be that it returns a false if the message is not being able to be parsed.

Thanks

**Comment by jaime-olivares** [comment]
The mechanism is explained in the very first section of the readme. The exception will show more useful information than a true/false response. The latter is reserved only for the case where the Parse operation didn't throw an error but couldn't interpret it accurately.

**Comment by Fjsmoreira** [comment]
Wouldn't it then make more sense to have the ParseMessage method be void and even in the case where it can't interpret throw an exception?

**Comment by jaime-olivares** [comment]
I am not changing a mechanism that is already being used by hundreds of users. I would break a lot of products using this library.
