### ISSUE TITLE
Parsing Date Time is depending on Culture variants

### ISSUE THREAD

**Issue by gokkep** [Efferent-Health/HL7-dotnetcore#69]
The code pointed to by the URL below is wrong, while it makes the parsing of a date time dependend on the current Culture variant of the run time system. It is using float.Parse which will not always work.

https://github.com/Efferent-Health/HL7-dotnetcore/blob/d71debe7e64035e4c9c85b9455948ab173cdbe6c/src/MessageHelper.cs#L55

My code threw exceptions while the number of seconds become higher then 60 so the DateTime creation failed.

Please use the following line of code to overcome this problem and make the parsing of date time independent of the Culture variants:

float fsecs = groups[6].Success ? float.Parse(groups[6].Value, CultureInfo.InvariantCulture) : 0;

**Comment by jaime-olivares** [comment]
Got it. I will fix and release soon.

**Comment by jaime-olivares** [comment]
Published in https://www.nuget.org/packages/HL7-dotnetcore/2.20.0
