### ISSUE TITLE
How do I include MSH.2?

### ISSUE THREAD

**Issue by kfrancis** [Efferent-Health/HL7-dotnetcore#7]
If I include the following code, then I get the exception [here](https://github.com/Efferent-Health/HL7-dotnetcore/blob/master/src/Encoding.cs#L123):

    var hl7Encoding = new HL7Encoding() { };
    var msh = new Segment("MSH", hl7Encoding);
    var msh_2 = new Field("MSH2", hl7Encoding);
    msh_2.Value = @"^~\&"; // problem here
    msh.AddNewField(msh_2);

How can I include MSH.2 with the value `^~\&` in the serialized message?

**Comment by jaime-olivares** [comment]
Hi,  I will need some time to review that. In the meantime, have a look to the implementation of GetAck() [here](https://github.com/Efferent-Health/HL7-dotnetcore/blob/master/src/Message.cs#L537) as a more manual alternative.

**Comment by jaime-olivares** [comment]
It seems easier to have a CreateMSH() method, as it needs a special treatment.

**Comment by StefanoD** [comment]
@kfrancis 
Why is this issue closed? I could not find any commit which fix this issue.

**Comment by jaime-olivares** [comment]
Reopening...

**Comment by jaime-olivares** [comment]
Added AddSegmentMSH()

**Comment by Fjsmoreira** [comment]
In my case i need to add more field to the MSH that are not present in the AddSegmentMSH.
What would you advice in that case ?
