### ISSUE TITLE
How to check if a message is a successful ACK message?

### ISSUE THREAD

**Issue by matthiashermsen** [Efferent-Health/HL7-dotnetcore#70]
Hey there, is there a way to check if a `Message` is a successful ACK message? Currently I'm using this extension method

```cs
    public static class MessageExtensions
    {
        public static bool IsSuccessful(this Message message)
        {
            string messageType = message.GetValue("MSH.9.1");

            return messageType == "ACK";
        }
    }
```

Maybe there is a better way to do it. Does this package provide something for it? If not, maybe you want to add a property or method to the `Message` class? :) 

Feel free to let me know if you want me to contribute to the class and the docs.

**Comment by jaime-olivares** [comment]
I will consider it for the incoming release
