### ISSUE TITLE
Message,  Segment and Field Values aren't being updated

### ISSUE THREAD

**Issue by mdrummond1** [Efferent-Health/HL7-dotnetcore#75]
The Serialize function only return a string of the most recently added segment.

 public void AddPatientID(List<string> pData, string rowNum)
        {
            Message m = new Message();
            msg.AddSegmentMSH("CSVtoHL7", pData[0], "", "", "", "ORU^R01", Program.GetRandomNumber(20), "P", "2.5.1");
            //outputs MSH|^~\&|CSVtoHL7|Lab|||20201203140806.3319||ORU^R01|14448181048448081687|P|2.5.1

            m.SerializeMessage(false);
            Segment s = new Segment("PID", new HL7Encoding());
            //| 1 |
            Field f = new Field("1", new HL7Encoding());
            s.AddNewField(f);
           
            //2 empty fields||||
            //s.AddEmptyField();
            

            //|LNAME ^ FNAME |
            f = new Field("King", new HL7Encoding());
            f.AddNewComponent(new Component("Linda", new HL7Encoding()));
            s.AddNewField(f);

            //|< dob >|
            f = new Field("1/1/1980", new HL7Encoding());
            s.AddNewField(f);

            //< gender >|
            f = new Field("F", new HL7Encoding());
            s.AddNewField(f);

            //< race >|
            f = new Field("B", new HL7Encoding());
            s.AddNewField(f);

            //< street > ^< city > ^< state > ^< zip > ^<County>|
            f = new Field("123 HOME STREET", new HL7Encoding());
            f.AddNewComponent(new Component("CHICAGO", new HL7Encoding()));
            f.AddNewComponent(new Component("IL", new HL7Encoding()));
            f.AddNewComponent(new Component("66213", new HL7Encoding()));
            s.AddNewField(f);

            //| ^< phone number > ^< device > ^^^< area code > ^< 7 - digit phone >|
            f = new Field("913" + "5555555", new HL7Encoding());
            f.AddNewComponent(new Component("PRN", new HL7Encoding()));
            f.AddNewComponent(new Component("PH", new HL7Encoding()));
            f.AddNewComponent(new Component("913", new HL7Encoding()));
            f.AddNewComponent(new Component("5555555", new HL7Encoding()));
            s.AddNewField(f);

            //|||||||| 7 empty fields
            for (int i = 0; i < 7; i++)
            {
                s.AddEmptyField();
            }

            //< ethnicity >|
            f = new Field("N", new HL7Encoding());
            s.AddNewField(f);

            
            msg.AddNewSegment(s);

           msg.SerializeMessage(false);
           //outputs PID|1|King^Linda|1/1/1980|F|B|123 HOME STREET^CHICAGO^IL^66213|9135555555^PRN^PH^913^5555555||||||||N
          
}

**Comment by jaime-olivares** [comment]
@mdrummond1  
I see you have combined the usage of `msg` and `m`. Can you provide a working sample code? Preferably as a pull request in the `/test` folder.

**Comment by mdrummond1** [comment]
So, I guess it's just the vs2019 debugger. When I print it out to a file, it works correctly, but in the debugger it will only show part of the message. I'll go ahead and close the issue.
