### ISSUE TITLE
GetValue does not decode encoded string data

### ISSUE THREAD

**Issue by gregstumph** [Efferent-Health/HL7-dotnetcore#76]
If an HL7 file contains encoded string data, the Message.GetValue method returns the data without decoding the encoded characters. I would expect that the encoded characters are decoded in the returned data.

For example, if an HL7 document contains a PID segment with a family name value that has encoded characters:
`PID|1||MRN_123^^^IDX^MRN||Smith\F\\S\\R\\E\\T\^John||19600101|M`

I would expect a call to Message.GetValue("PID.5.1") to return "Smith|^~\&", but instead it returns "Smith\\F\\\\S\\\\R\\\\E\\\\T\\".

As a workaround, I can wrap every call to GetValue for data that may be encoded with a call to Encoder.Decode. But it would be nice if the library did this automatically.

**Comment by jaime-olivares** [comment]
This should be solved in version 2.21 ( https://www.nuget.org/packages/HL7-dotnetcore/2.21.0 )

**Comment by jaime-olivares** [comment]
Have a look at the GetValueTest() test method
