### ISSUE TITLE
Invalid escape sequence in HL7 

### ISSUE THREAD

**Issue by AlexKulbako** [Efferent-Health/HL7-dotnetcore#77]
Message:
````
MSH|^~\&|TEST^TEST|TEST|||11111||ADT^A08|11111|P|2.4|||AL||D||||||
EVN|A08|11111111||16|||
PID|1|11111^^^&TEST&L|11111^^^&TEST&L||TEST^TEST^^^^||11111|M||0^0^0^0^0|TEST. 3^^TEST^^11111^D^H|||||KE||||||||||D||||N||||||||
PV1|1|I|SE1^SE1 A 11^SE1 A 11 3^NCHHA|^||^^^^||67676&1341988^Al TEST^TEST TEST^^^^^^^^T^^^^^TEST 69^49076^TEST^D^V^111-222&WPN&PH^^Herr&Sehr geehrter TEST^11111^6767^N^TEST für TEST||||||268056252||0|||370256^^^&TEST&L^&TEST&L^&TEST&L^6767677^||X|||^stat^GK^|5656565|||^|||||||||||||N|||5656||||||565^^&TEST&L^&TEST&L^^20201229114300^^293998^787^787||
PV2|||0101^4901||||||6767676767|8||||||||||||||E^||||||||||||N|||||||||||
Z00|1|139378|20201230100000|ghg^ghgh-HA||s1^OP-Saal 1|gh^gjhg 1|ghg^ghjg-HA|**BSV 4\5 re.||||||**
Z01|1|139378|20201230100000|6g^OP-gjhgjh 1|S^ghjgjh^1|||gjhg^ghjgjh 1 - ghjg ghjg ghjg|gr1^gjhg 1 - Nicht gjhgjh Region||
````

Problem with Z00|1|139378|20201230100000|ghg^ghgh-HA||s1^OP-Saal 1|gh^gjhg 1|ghg^ghjg-HA|**BSV 4\5 re.||||||**
method Decode()

**Comment by AlexKulbako** [comment]
@jaime-olivares could you please help with it ?

**Comment by jaime-olivares** [comment]
Hi @AlexKulbako ,
I have reviewed the HL7 specification and cannot find that scenario. It seems to be invalid.
Check: http://healthstandards.com/blog/2006/11/02/hl7-escape-sequences/ 
Let me know if there is another source describing that scenario and how to proceed

**Comment by AlexKulbako** [comment]
Thank you very much for reply @jaime-olivares . I think this is a problem with this text: 'BSV 4\5 re.' and this symbol '\'
This is some medical result from third-party system. I tried the same message with trial version of https://www.hermetechnz.com/EasyHL7/Prod_Listeners.asp and it was parsed successfully .

**Comment by jaime-olivares** [comment]
Hi @AlexKulbako  
I can see that your custom segments Z00 and Z01 don't comply with the valid format. As far as I know, segment names, even custom Z ones, shall follow the pattern A-Z / A-Z / A-Z1-9
Having solved that, it is passing with the new version 2.22 ( https://www.nuget.org/packages/HL7-dotnetcore/2.22.0 )
