### ISSUE TITLE
Setting encoding and then adding MSH segment on Message throws

### ISSUE THREAD

**Issue by nagonigi** [Efferent-Health/HL7-dotnetcore#79]
Creating a new message, followed by adding a custom HL7Encoding before doing .AddSegmentMSH throws HL7Exception stating "MSH segment doesn't contain all the required fields.". Doing the same thing but without setting .Encoding does not throw the same error. See sample code below.

            var encoding = new HL7Encoding 
            {
                FieldDelimiter = '1',
                ComponentDelimiter = '2',
            };
            var message = new Message();
            message.Encoding = encoding;
            message.AddSegmentMSH("asdasd", "dsadsa", "asdasdasd", "dsadasdasd",
                "qweqwe", "ORU^R01^ORU_R01", "iuhqwieuh, "zxczxczxc", "2.8");

Commenting out "message.Encoding = encoding;" makes the code not throw.

**Comment by jaime-olivares** [comment]
This should be solved in version 2.21 ( https://www.nuget.org/packages/HL7-dotnetcore/2.21.0 )
