### ISSUE TITLE
Custom HL7Encoding with ComponentDelimiter does not set delimiter field correctly

### ISSUE THREAD

**Issue by nagonigi** [Efferent-Health/HL7-dotnetcore#80]
Setting a custom HL7Encoding before message serialization does not yield expected result.

            var encoding = new HL7Encoding 
            {
                FieldDelimiter = '1',
                ComponentDelimiter = '2',
            };
            var message = new Message();
            message.AddSegmentMSH("asdasd", "dsadasd", "asdasd", "dsadsa",
                "dsadasdas", "ORU^R01^ORU_R01", "asdasdas", "asdasd", "2.8");
            message.Encoding = encoding;
            var result = message.SerializeMessage(false);

Yields a message starting like 
"MSH1^\~\&1"
Expected 
"MSH12\~\&1".

**Comment by jaime-olivares** [comment]
This should be solved in version 2.21 ( https://www.nuget.org/packages/HL7-dotnetcore/2.21.0 ) 

Your example has some issues:
- The Encoding shall be set before AddSegmentMSH
- The messageType string shall be encoded already, as ^ is not a valid delimiter and 1 is a special character

Have a look at the CustomDeliminerTest() method in the test suite.

**Comment by nagonigi** [comment]
Yes you are right, the Encoding shall be set before AddSegmentMSH (although this caused an exception to be thrown before 2.21). I copied the logic of CustomDelimiterTest to my machine, and get an exception "HL7.Dotnetcore.HL7Exception: 'Failed to validate the message with error - MSH segment doesn't contain all the required fields'".
