### ISSUE TITLE
HL7Encoding.Encode() injects extra 0 in \Xnn\ escape sequence. 

### ISSUE THREAD

**Issue by JeffKelly-Spok** [Efferent-Health/HL7-dotnetcore#81]
We have observed the HL7Encoding.Encode() method escaping the non-printable hexadecimal characters with an extra leading zero. 
For example: `\r` resolves to `\X00D\`.  

This is not a critical issue for us since it is still a valid hexadecimal value, but we are expecting some users may encounter pushback from consuming systems. 

The conditional statement at [Line 96 in Encoding.cs](https://github.com/Efferent-Health/HL7-dotnetcore/blob/9c3945bed2693cf60d257a920fb2504cf0b9887c/src/Encoding.cs#L96) performs a logical OR check of the hex digit string's length with 2, which is always nonzero. 

Instead of using: 
```
if ((v.Length | 2) != 0) 
```

You could use:
```
if ((v.Length % 2) != 0) 
```

The modulus will return nonzero if v.Length is an odd number.

**Comment by jaime-olivares** [comment]
Fixed in 2.24. Thanks for the PR.
