### ISSUE TITLE
HL7Encoding doesn't handle <BR>, <B> and </B> in Encode()

### ISSUE THREAD

**Issue by domibies** [Efferent-Health/HL7-dotnetcore#82]
The Encode() method doesn't handle special cases for "\.br\", "\H\" en "\N\". These are converted to `<BR>`, `<B>` and `</B>` in the Decode() method, but are not converted back in Encode().

You can check this by adding the following segment line to Sample-ORM.txt

`NTE|1||some text\.br\some text after \H\new line\H\
`

If you then change Main() in Program.cs to 

`        public static void Main(string[] args)
        {
            var test = new HL7Test();
            test.ParseTest1();
        }`

the HL7Test console app fails because isParsed is set to false in the Encode() method (after comparing the serialized HL7 to the original string)

**Comment by jaime-olivares** [comment]
Fixed in 2.24. Thanks for the PR.
