### ISSUE TITLE
HL7Encoding.Encode in version 2.24.0 removes "<" signs

### ISSUE THREAD

**Issue by DavidErben** [Efferent-Health/HL7-dotnetcore#86]
Hello,

I have encountered an issue with the latest version 2.24.0 of your library. While serializing a HL7 message, the "<" signs gets removed in the segment fields, f.e. in an OBX segment.

**Version 2.24.0:**
`new HL7Encoding().Encode("<1") = "1"`

**Version 2.23.0:**
`new HL7Encoding().Encode("<1") = "<1"`

**Test HL7 to reproduce:**
> MSH|^~\&|LAB|LC|003|0001|20141022085632||ORU^R01|20141022085632|P|2.2||||||8859/1|D
PID|1|0|0|||||||||||||
OBR|1|||||20140710091116|20140710091116|||||||20140710091116|||||||||||F|
ORC|RE||20140710091116||CM|||||LC||000000|||20140710091116|||N2_LABOR^001||
OBX|0001|NM|HbA1c^HbA1c||8.2|%|**_<6.50_**|AA|||F|||20130923085848||

The problematic code:

> if (ch == '<')
        {
          if (val.Length >= index + 3 && val[index + 1] == 'B' && val[index + 2] == '>')
          {
            stringBuilder.Append(this.EscapeCharacter);
            stringBuilder.Append("H");
            stringBuilder.Append(this.EscapeCharacter);
            index += 2;
          }
          if (val.Length >= index + 4 && val[index + 1] == '/' && val[index + 2] == 'B' && val[index + 3] == '>')
          {
            stringBuilder.Append(this.EscapeCharacter);
            stringBuilder.Append("N");
            stringBuilder.Append(this.EscapeCharacter);
            index += 3;
          }
          if (val.Length >= index + 4 && val[index + 1] == 'B' && val[index + 2] == 'R' && val[index + 3] == '>')
          {
            stringBuilder.Append(this.EscapeCharacter);
            stringBuilder.Append(".br");
            stringBuilder.Append(this.EscapeCharacter);
            index += 3;
          }
        }

Change has been made by @domibies

Thanks for your help!

**Comment by domibies** [comment]
Yes, sorry, I have noticed it myself, and have fixed this in our own fork called 'HL7lite' (we need a fork that is a little more flexible, so we're using this in our own projects)

If I have time later I'll fix it in this fork as well.

You can find this in https://github.com/domibies/HL7lite/blob/master/src/Encoding.cs

**Comment by Ravenheart** [comment]
Why not merge it back to this repo.

**Comment by jaime-olivares** [comment]
Solved. To be released soon.
