### ISSUE TITLE
Bypass Validation

### ISSUE THREAD

**Issue by BenSinnott** [Efferent-Health/HL7-dotnetcore#91]
Hi, firstly... love this library 👍 
I'm probably missing something here, but the bypass validation parameter (as documented in the read me) is is missing from message.ParseMessage in 2.24.0.

I ask because I am processing messages that have not populated the Processing ID segment (MSH.11) and would like to allow these through.

Was it removed for some reason?

**Comment by Ravenheart** [comment]
Afaik that commit hasn't been released to Nuget yet.

**Comment by jakepeacock-bh** [comment]
Also wondering because the 2.24 release still does not recognize utilizing ParseMessage with the new parameter.

**Comment by jakepeacock-bh** [comment]
Curious when the next upcoming release to NuGet will be. It's likely I cannot utilize this library until the Bypass Validation logic is available.

**Comment by jaime-olivares** [comment]
I have just released but not PR #94 as it has a pending observation

**Comment by jaime-olivares** [comment]
merged #94 
Will release soon
