### ISSUE TITLE
GetValue and \"\"

### ISSUE THREAD

**Issue by ghust** [Efferent-Health/HL7-dotnetcore#92]
Hi guys,

I'm currently working on an implementation and I'm trying to apply HL7 logic following:;

- If the value of a field is empty, do nothing with the property
- If the value of the field is two quotes, clear the property
- If the value of the field is something else, set the property to the value.

I see that the GetValue doesn't apply this logic, and I'm either wondering how we could fix this or if there's another way to get the desired outcome :)

This is a unit test that demonstrates the behavior:

        public void GetValueShouldReturnQuotesInsteadOfNull()
        {
            // Arrange
            Message message = new Message();
            
            Segment segment = new Segment("OBR", new HL7Encoding());
            segment.AddNewField("\"\"", 1);
            message.AddNewSegment(segment);

            // Act
            var resultingstring = message.GetValue("OBR.1");

            // Assert
            
            Assert.AreEqual("\"\"", resultingstring);
        }

**Comment by ghust** [comment]
`        public void GetValueShouldReturnQuotesInsteadOfNull()
        {
            // Arrange
            Message message = new Message();
            
            Segment segment = new Segment("OBR", new HL7Encoding());
            segment.AddNewField("\"\"", 1);
            message.AddNewSegment(segment);

            // Act
            var resultingstring = message.GetValue("OBR.1");

            // Assert
            
            Assert.AreEqual("\"\"", resultingstring);
        }`

**Comment by ghust** [comment]
I think I misread the code, and GetValue should throw an exception when the field is not found, thus allowing me that behavior.

**Comment by ghust** [comment]
Adding to this:

MessageElement.cs : 12

`return _value == Encoding.PresentButNull ? null : _value; `

This makes sure that there isn't a way to differentiate between HL7 null and an empty segment, or am I mistaken?

**Comment by manosg80** [comment]
I think this is related to this:

https://github.com/nHapiNET/nHapi/issues/414

**Comment by jaime-olivares** [comment]
Hi @ghust,

If this behavior is not desirable, it can be disabled by setting `Encoding.PresentButNull` to `null` before parsing:

````cSharp
var message = new Message(msg);
message.Encoding.PresentButNull = null;
message.ParseMessage();
`````
