### ISSUE TITLE
Line breaks

### ISSUE THREAD

**Issue by ascazzola** [Efferent-Health/HL7-dotnetcore#93]
Hello,

I'm using the library and when I obtain a value from a MessageComponent the break lines as \\.br\ are replaced with the string  \<BR>\.

I want to use \r\n instead, but I want to ask if there are any reason to change the \\.br\ to \<BR>\.

Thanks and best regards

**Comment by jaime-olivares** [comment]
Hi, this is mostly an arbitrary decision: most applications are nowadays web-based, it could be also \r\n or even \n\r.
With that criteria, I am leaving it as is.
