### ISSUE TITLE
DeepCopy doesn't copy fields with values

### ISSUE THREAD

**Issue by MDzyga** [Efferent-Health/HL7-dotnetcore#97]
Hi,
We have a scenario when we have to prepare a few segments INV and repeat them after each OBX segments.
We would like to use DeepCopy but it copies only Value and we get new segment with only name.

Our current code looks:
```
var helperMessage = new CustomMessage(" ");
helperMessage.GenerateInvSegments(inventories);
ICollection<Segment> invSegments = helperMessage.Segments(SegmentHeaders.INV);
```
next we have to do:
```
message.AddSegments(invenstories);

void AddSegments(this Message message, ICollection<Segment> segments)
{
  foreach (var segment in segments)
  {
    var newSegment = segment.DeepCopy();
    foreach (Field field in segment.GetAllFields())
    {
        newSegment.AddNewField(field);
    }

    message.AddNewSegment(newSegment);
  }
}
```

Do we use it incorrectly?

**Comment by jaime-olivares** [comment]
Hi,
I am wondering why you use foreach/AddNewField if `newSegment` may be already filled in. I think the source code should look like: 
````
void AddSegments(this Message message, ICollection<Segment> segments)
{
  foreach (var segment in segments)
  {
    var newSegment = segment.DeepCopy();

    message.AddNewSegment(newSegment);
  }
}
````

On the other hand, I don't know whether `inventories` contains valid information and how `invSegments` relates to it.

**Comment by MDzyga** [comment]
@jaime-olivares DeepCopy doesn't copy fields with their values

**Comment by jaime-olivares** [comment]
DeepCopy won't work with a segments generated on the fly.

You need to create a message:
`var m = new Message();`
Add the segments to the message:
`m.AddNewSegment(s);  // several times`
and serialize the whole message:
`var s = m.SerializeMessage(false);`
Then read that string into a new message:
`mar m2 = new Message(s);`

Now you will be able to clone the segments contained in `m2`
